---
- name: Create project root directory
  file: |
    path={{ root_dir }} state=directory
    owner={{ user_name }} group={{ user_name }}

- name: Checkout agent source code from git
  git: |
    repo=https://github.com/scratch-userland/user-service.git
    dest={{ source_dir }} version={{ git_deploy_version }} force=yes accept_hostkey=yes

- name: Change some directories owner and group
  file: |
    path={{ source_dir }}/app/static state=directory recurse=yes
    owner=www-data group=www-data
